# -*- coding: utf-8 -*-
"""Social media analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fARF41XLvZpYhBcrU3YsUexRwO2_MJA
"""

#POST ACTIVITY ACROSS PLATFORMS
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("sentimentdataset.csv")

# Convert timestamp to datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

sns.set(style="whitegrid", palette="muted")

# Group by hour and platform
hourly_platform = df.groupby(['Hour', 'Platform']).size().reset_index(name='Post_Count')

# Sort hours
hourly_platform = hourly_platform.sort_values('Hour')

# Plot multi-line time series
plt.figure(figsize=(10,6))
sns.lineplot(data=hourly_platform, x='Hour', y='Post_Count', hue='Platform', marker='o', linewidth=2.5)

plt.title("Posting Activity by Hour Across Platforms", fontsize=14)
plt.xlabel("Hour of Day (24-hour format)")
plt.ylabel("Number of Posts")
plt.xticks(range(0, 24))
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title="Platform", loc="upper left")
plt.tight_layout()
plt.show()

#WORD CLOUD — Most Common Hashtags
from wordcloud import WordCloud
import matplotlib.font_manager as fm

# Combine all hashtags into a single string
hashtags_text = " ".join(df["Hashtags"].dropna().astype(str).values)

# Ensure a TrueType font for compatibility
font_path = fm.findfont("DejaVuSans")

# Generate and display word cloud
wordcloud = WordCloud(width=1000, height=600, background_color='white',
                      colormap='plasma', font_path=font_path).generate(hashtags_text)

plt.figure(figsize=(10,6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("☁️ Most Common Hashtags in Posts", fontsize=14)
plt.show()

#AVG POSTS PER COUNTRY
df['Country'] = df['Country'].str.strip().str.title()  # remove spaces and standardize capitalization

# 🧮 Count posts per country
# ---------------------------------------------
post_activity = df['Country'].value_counts().reset_index()
post_activity.columns = ['Country', 'Post_Count']

# 🎨 Bar Chart — Posting Activity
# ---------------------------------------------
plt.figure(figsize=(10,6))
sns.barplot(data=post_activity.head(15), x='Country', y='Post_Count', palette='coolwarm')

plt.title("Average Posting Activity by Country", fontsize=15, weight='bold')
plt.xlabel("Country", fontsize=12)
plt.ylabel("Number of Posts", fontsize=12)
plt.xticks(rotation=30, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()